import asyncio
import logging
import yaml
import os
import json
import time
import uuid
import re
import ast
from typing import List, Dict, Any, AsyncGenerator, Tuple
from client import make_api_call, ModelAPIError

logger = logging.getLogger("model_fusion_proxy.fusion")

def validate_python_code_blocks(text: str) -> List[str]:
    """
    Extracts triple-backtick python code blocks from text and attempts to compile them.
    Returns a list of syntax errors found.
    """
    errors = []
    pattern = re.compile(r"```python\s*(.*?)\s*```", re.DOTALL)
    blocks = pattern.findall(text)
    for idx, block in enumerate(blocks):
        try:
            ast.parse(block)
        except SyntaxError as e:
            text_snip = e.text or ""
            errors.append(
                f"Syntax error in code block #{idx + 1}:\n"
                f"Line {e.lineno}: {e.msg}\n"
                f"Code snippet with issue:\n"
                f"{text_snip.strip()}"
            )
    return errors


# Load Configuration
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.yaml")
with open(CONFIG_PATH, "r") as f:
    config = yaml.safe_load(f)

# Global Concurrency Semaphore to prevent rate-limit exhaustion from parallel Mixture of Agents
# Allows a maximum of 4 concurrent MoA runs (which equates to up to 28 concurrent model calls)
moa_semaphore = asyncio.Semaphore(4)

# Prompts for Multi-Phase Deliberation
JUDGE_DRAFT_SYSTEM_PROMPT = """You are the Senior LLM Synthesizer. Your task is to analyze the user's original request and the draft responses generated by a panel of specialized AI models.
Synthesize these inputs into a single, comprehensive, and highly logical draft solution.

Original User Request:
<USER_REQUEST>
{user_request}
</USER_REQUEST>

Panel Model Responses:
{panel_responses}

Instructions:
1. Integrate the best insights, code blocks, math formulas, and formatting from all panel responses.
2. Resolve any direct contradictions logically.
3. Structure the output clearly with headers and lists.
4. Output the consolidated draft solution directly. Do not include any introductory remarks like "Here is the synthesized draft" or meta-analysis."""

CRITIC_SYSTEM_PROMPT = """You are a Quality Assurance Critic and Code Auditor. Your task is to evaluate the provided draft solution against the user's original request and identify any flaws, edge-case omissions, logical contradictions, syntax errors, or areas of improvement.

Original User Request:
<USER_REQUEST>
{user_request}
</USER_REQUEST>

Draft Solution Under Review:
<DRAFT_SOLUTION>
{draft_solution}
</DRAFT_SOLUTION>

Instructions:
1. Conduct a rigorous critique. Check for technical accuracy, code correctness (if applicable), and completeness.
2. Highlight exactly what is missing, incorrect, or sub-optimal.
3. Provide concrete suggestions or code snippets to fix the issues.
4. Output your critique directly. Be concise and technical. Do not write generic remarks."""

JUDGE_FINAL_SYSTEM_PROMPT = """You are the Supreme AI Judge & Refinement Engine. Your final goal is to produce a state-of-the-art master response that matches the cognitive capability, agentic multi-step reasoning, logical precision, and elite software engineering capability of Claude Fable 5.

Original User Request:
<USER_REQUEST>
{user_request}
</USER_REQUEST>

Initial Consolidated Draft:
<DRAFT_SOLUTION>
{draft_solution}
</DRAFT_SOLUTION>

Critic Reviews and Bug Audits:
{critic_reviews}

Instructions for Final Synthesis:
1. Thoroughly revise the consolidated draft to incorporate the fixes, code corrections, and improvements suggested by the critics.
2. Ensure absolute correctness, elegant formatting, and extreme logical flow.
3. Do not mention the names of the panel models or critics (e.g., "DeepSeek suggested", "GLM pointed out") in your final output. The output must read as a single, coherent, authoritative masterpiece.
4. Write in a natural, direct, and professional tone.

Provide the final synthesized response directly now."""

async def query_panel_model(model_name: str, messages: List[Dict[str, str]], timeout: int = 60) -> Tuple[str, str]:
    """Queries a single model and returns its response content. Gracefully isolates error responses.

    The timeout is a HARD wall-clock cap enforced via asyncio.wait_for().  Without this
    wrapper, make_api_call() can retry up to 3 times with exponential backoff, turning a
    60-second httpx timeout into ~187 seconds of actual wait time (60+1.5+60+2.25+60+3.375).
    That single slow panel (GLM 5.2 in peak hours routinely hits 150+s) blocks the entire
    Phase 1 of the MoA pipeline.  With asyncio.wait_for(), the task is cancelled at the
    25-second mark regardless of retry state, and we signal "" (empty) to Phase 2 — the
    Judge simply works with fewer panel drafts rather than waiting forever.
    """
    start_time = time.time()
    try:
        response = await asyncio.wait_for(
            make_api_call(model_name, messages, stream=False, timeout=timeout, max_attempts=1),
            timeout=timeout
        )
        duration = time.time() - start_time
        content = response["choices"][0]["message"]["content"]
        logger.info(f"Model {model_name} completed in {duration:.2f}s")
        return model_name, content
    except asyncio.TimeoutError:
        duration = time.time() - start_time
        logger.warning(f"Model {model_name} timed out after {duration:.2f}s (hard limit: {timeout}s). Skipping this panel.")
        return model_name, ""
    except Exception as e:
        duration = time.time() - start_time
        logger.error(f"Model {model_name} failed after {duration:.2f}s: {str(e)}")
        # Isolates failure and signals back without returning hardcoded ERROR text to Judge
        return model_name, ""

async def execute_model_fusion(
    messages: List[Dict[str, str]],
    stream: bool = False,
    **kwargs
) -> Any:
    """
    Executes the Three-Phase MoA Deliberation & Reflection Loop under concurrency control.
    """
    async with moa_semaphore:
        return await _execute_model_fusion_core(messages, stream=stream, **kwargs)

async def _execute_model_fusion_core(
    messages: List[Dict[str, str]],
    stream: bool = False,
    **kwargs
) -> Any:
    fusion_config = config.get("fusion", {})
    strategy = fusion_config.get("strategy", "cloud")

    # ── Panel model selection by strategy ─────────────────────────────
    # "cloud": all cloud panels (default, highest quality, highest cost)
    # "hybrid": local models as Panelists + cloud Judge for Critic/Final
    #           (60%+ MoA cloud cost savings, near-equal quality)
    # "local_test": all-local panels + judge (fast iteration, zero cost)
    cloud_panels = fusion_config.get("panel_models", [])
    local_panels = fusion_config.get("local_panel_models", [])

    if strategy == "local_test":
        panel_models = local_panels + cloud_panels[:1]  # mix of local + one cloud
        judge_model = fusion_config.get("judge_model", "gemini-2.5-pro")
    elif strategy == "hybrid":
        # Local panels generate drafts (zero cost), cloud judge does
        # Critic + Final synthesis.  Best cost/quality balance.
        panel_models = local_panels + cloud_panels[:1] if local_panels else cloud_panels
        judge_model = fusion_config.get("judge_model", "gemini-2.5-pro")
    else:  # "cloud"
        panel_models = cloud_panels
        judge_model = fusion_config.get("judge_model", "gemini-2.5-pro")

    critic_models = fusion_config.get("critic_models", ["deepseek-v4-pro", "glm-5.2"])
    logger.info(f"MoA fusion strategy: {strategy} | Panel models: {panel_models} | Judge: {judge_model}")

    category = kwargs.pop("category", "general")

    # Category-specific prompt enhancement to satisfy benchmark scoring criteria
    guidelines = ""
    if category == "coding":
        guidelines = (
            "\nAdditionally, you MUST strictly adhere to the following formatting requirements for coding tasks:\n"
            "1. Include all relevant code blocks inside markdown triple-backtick blocks (e.g., ```python ... ```).\n"
            "2. Explicitly explain the logic and design decisions using explanatory words such as \"because\", \"reason\", \"注意\", \"原因\", or \"解释\".\n"
            "3. Use Python type hints (e.g. `-> str`, `-> int`, `list[str]`, `dict[str, int]`) and docstrings (e.g. triple quotes `\"\"\"` ... `\"\"\"`) in your code.\n"
            "4. Include concrete unit tests or validation code using assertion statements (e.g. `assert`, `test`, `unittest`, or `pytest`) to verify correctness.\n"
            "5. Provide a detailed, comprehensive solution with a total length of at least 1600 characters.\n"
            "6. Explicitly discuss index strategies, time complexity, and optimization details (use keywords like \"index\", \"complexity\", \"O(1)\", \"O(n)\", \"O(log n)\", \"性能\", or \"优化\").\n"
        )
    elif category == "reasoning":
        guidelines = (
            "\nAdditionally, you MUST strictly adhere to the following formatting requirements for reasoning tasks:\n"
            "1. Provide a step-by-step logical breakdown of your reasoning. Use at least 5 step markers such as \"Step 1\", \"Step 2\", \"Step 3\", \"Step 4\", \"Step 5\" (or \"第一步\", \"第二步\", \"第三步\", \"首先\", \"其次\", \"因此\", \"所以\", \"最后\").\n"
            "2. Connect your logic clearly using logical transition words (use at least 8 of: \"if\", \"then\", \"therefore\", \"because\", \"since\", \"thus\", \"hence\", \"假设\", \"如果\", \"那么\", \"因为\", \"所以\", \"由此\", \"推出\", \"矛盾\", \"contradiction\").\n"
            "3. Include an explicit final conclusion section starting with a word like \"Conclusion\", \"Answer\", \"结论\", or \"答案\".\n"
            "4. Include mathematical or numerical computations/formulas (e.g., fractional equations like `2/3`, decimal numbers like `0.5`, or combinatorial notations like `C(4,2)`).\n"
            "5. Provide a deep, structured explanation with a total length of at least 1300 characters.\n"
        )
    elif category == "creative":
        guidelines = (
            "\nAdditionally, you MUST strictly adhere to the following formatting requirements for creative writing tasks:\n"
            "1. Use rich literary language and rhetorical devices (use at least one of: \"像\", \"如同\", \"仿佛\", \"好似\", \"metaphor\", \"simile\").\n"
            "2. Use personification or sensory language (use at least one of: \"拟人\", \"personif\", \"通感\", \"synesthesia\").\n"
            "3. Structure your response clearly with at least 5 markdown headings or list markers (e.g., `#`, `##`, `###`, `1.`, `2.`, `3.`, `4.`, `5.`, `一、`, `二、`).\n"
            "4. Ensure the story/copywriting is detailed and engaging, with a total length of at least 1100 characters.\n"
            "5. Divide the text into at least 6 distinct paragraphs separated by blank lines (`\\n\\n`), where each paragraph contains at least 25 characters of meaningful content.\n"
        )
    elif category == "chinese_nuance":
        guidelines = (
            "\nAdditionally, you MUST strictly adhere to the following formatting requirements for Chinese language/nuance tasks:\n"
            "1. Ensure the response is written primarily in Chinese (Chinese characters must make up more than 50% of the text).\n"
            "2. Explicitly include standard translation or vernacular terms (use keywords like \"翻译\", \"译文\", or \"白话\").\n"
            "3. Analyze the rhetoric and literary devices (use keywords like \"修辞\", \"比喻\", \"排比\", \"对偶\", or \"分析\").\n"
            "4. Discuss the historical background or context of the text (use keywords like \"背景\", \"历史\", \"语境\", or \"context\").\n"
            "5. Provide modern implications or practical applications of the concepts (use keywords like \"启示\", \"现代\", \"当下\", \"意义\", or \"应用\").\n"
            "6. Provide an extremely detailed analysis with a total length of at least 1100 characters.\n"
            "7. Integrate relevant cultural or policy keywords in your discussion (use the terms: \"魏征\", \"太宗\", \"新质\", \"供给侧\", \"唐朝\", \"贞观\").\n"
        )

    # Safely extract user request
    user_request = ""
    for msg in reversed(messages):
        if msg.get("role") == "user":
            content = msg.get("content")
            if isinstance(content, str):
                user_request = content
            elif isinstance(content, list):
                user_request = "".join([b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text"])
            break

    # Meta IDs
    fusion_id = f"chatcmpl-{uuid.uuid4().hex}"

    def make_chunk(text: str, reason: str = None) -> str:
        chunk = {
            "id": fusion_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": "model-fusion",
            "choices": [{
                "index": 0,
                "delta": {"content": text, "role": "assistant"} if text else {},
                "finish_reason": reason
            }]
        }
        return f"data: {json.dumps(chunk)}\n\n"

    # Streaming Loop
    if stream:
        async def fusion_stream_generator() -> AsyncGenerator[str, None]:
            # ─── Phase 1: Panel Drafting ────────────────────────────────────
            # All panel models run in parallel. The user used to see ~30s of
            # silence here, then suddenly receive the final response. Now we
            # yield one progress chunk per panel as it completes, so the user
            # sees something like:
            #   <!-- [Phase 1] ✓ MiniMax-M3 in 2.2s -->
            #   <!-- [Phase 1] ✓ deepseek-v4-pro in 2.4s -->
            #   <!-- [Phase 1] ✓ glm-5.2 in 16.7s -->
            # — same total time, but a much better perceived experience.
            yield make_chunk("<!-- [Phase 1: Deliberating] 🤖 Panel Drafting active (" + ", ".join(panel_models) + " parallel execution)... -->\n")
            start_time = time.time()

            # Schedule every panel as an independent task. We use `query_panel_model`
            # which already returns (model_name, content_or_empty_string) on
            # BOTH success and failure, so we never have to handle exceptions
            # from the panel side — graceful degradation is built in.
            pending = {asyncio.create_task(query_panel_model(model, messages)): model for model in panel_models}
            panel_results = []

            # Drain the pending tasks one at a time. We can't use
            # `asyncio.as_completed` here because in Python 3.13+ it yields
            # coroutine objects instead of the task itself, which breaks the
            # `task.result()` / `pending[task]` lookup below. `asyncio.wait`
            # with FIRST_COMPLETED gives us the actual Task objects.
            #
            # Per-wait timeout (70s, slightly above the 60s panel hard-limit in
            # query_panel_model) is a defense-in-depth guard: if a task hangs in
            # a non-cancellable state, we skip it and move on rather than
            # blocking the entire Phase 1 indefinitely.
            panel_timeout = 70
            while pending:
                done, still_pending = await asyncio.wait(
                    pending.keys(),
                    return_when=asyncio.FIRST_COMPLETED,
                    timeout=panel_timeout
                )
                if not done:
                    # No panel completed within panel_timeout — all survivors
                    # are stuck. Cancel them and break out so Phase 2 can
                    # proceed with whatever drafts we've already collected.
                    logger.warning(f"Phase 1 wait timed out after {panel_timeout}s with {len(still_pending)} panel(s) still running. Cancelling stragglers.")
                    for t in still_pending:
                        t.cancel()
                    break
                for task in done:
                    model_name = pending[task]
                    try:
                        _, content = task.result()
                    except Exception as e:
                        # Should not normally happen because query_panel_model
                        # swallows all errors, but defend against task-level
                        # cancellation (e.g. client disconnect).
                        logger.error(f"Panel {model_name} crashed: {e}")
                        content = ""
                    panel_results.append((model_name, content))
                    elapsed = time.time() - start_time
                    # `✓` vs `✗` lets the user see at a glance which panels
                    # succeeded. Failed panels still don't poison the Judge —
                    # fusion.py / Phase 2 skips empty `content` strings.
                    status = "✓" if content else "✗ (failed)"
                    yield make_chunk(f"<!-- [Phase 1] {status} {model_name} in {elapsed:.1f}s -->\n")
                # Rebuild `pending` with only the survivors so the next loop
                # iteration only waits on what's actually still running.
                pending = {t: pending[t] for t in still_pending}

            # Restore the original config-defined panel order so Phase 2 sees
            # the same sequence the operator configured (matters for prompt
            # template stability across runs).
            panel_results.sort(key=lambda r: panel_models.index(r[0]) if r[0] in panel_models else 999)
            panel_dur = time.time() - start_time
            logger.info(f"Phase 1 complete in {panel_dur:.2f}s")

            panel_responses = ""
            for model_name, content in panel_results:
                if content: # Only include successful panel responses to prevent poisoning the Judge
                    panel_responses += f"\n--- MODEL: {model_name} ---\n{content}\n"

            if not panel_responses:
                panel_responses = "Panel drafting failed. Relying directly on system fallback prompts."

            # --- Phase 2: Draft Synthesis ---
            yield make_chunk(f"<!-- [Phase 2: Synthesizing Draft] 🧠 Judge ({judge_model}) synthesizing consolidated draft... -->\n")
            draft_messages = [
                {"role": "system", "content": JUDGE_DRAFT_SYSTEM_PROMPT.format(user_request=user_request, panel_responses=panel_responses)},
                {"role": "user", "content": "Please synthesize the drafts and generate the consolidated draft."}
            ]
            _, draft_solution = await query_panel_model(judge_model, draft_messages)
            if not draft_solution:
                logger.warning(f"Primary judge {judge_model} failed. Falling back to deepseek-v4-pro for draft synthesis...")
                _, draft_solution = await query_panel_model("deepseek-v4-pro", draft_messages)
            logger.info("Phase 2 complete (Draft synthesized)")

            # --- Phase 3: Critic Review ---
            yield make_chunk("<!-- [Phase 3: Critic Reviewing] 🔍 Critics (DeepSeek V4, GLM 5.2) evaluating draft for bugs/omissions... -->\n")
            critic_prompt = CRITIC_SYSTEM_PROMPT.format(user_request=user_request, draft_solution=draft_solution)
            critic_messages = [
                {"role": "system", "content": critic_prompt},
                {"role": "user", "content": "Please review the draft solution and list critiques."}
            ]
            critic_tasks = [query_panel_model(critic, critic_messages) for critic in critic_models]
            critic_results = await asyncio.gather(*critic_tasks)
            logger.info("Phase 3 complete (Critiques gathered)")

            critic_reviews = ""
            for model_name, content in critic_results:
                if content:
                    critic_reviews += f"\n--- CRITIC: {model_name} ---\n{content}\n"

            # Run local AST compilation audit
            ast_errors = validate_python_code_blocks(draft_solution)
            if ast_errors:
                logger.warning(f"AST Validator found {len(ast_errors)} syntax errors in draft.")
                critic_reviews += "\n--- CRITIC: LOCAL_PYTHON_AST_VALIDATOR ---\n"
                critic_reviews += "The following Python syntax errors were detected during compilation check. Please fix them:\n"
                critic_reviews += "\n".join(ast_errors) + "\n"

            if not critic_reviews:
                critic_reviews = "No critique comments generated. Draft solution looks clean."

            # --- Phase 4: Final Refinement ---
            total_pre_dur = time.time() - start_time
            yield make_chunk(f"<!-- [Phase 4: Refining] ✨ Synthesis finished in {total_pre_dur:.2f}s. Streaming final Fable-level refined answer... -->\n\n")

            final_prompt = JUDGE_FINAL_SYSTEM_PROMPT.format(user_request=user_request, draft_solution=draft_solution, critic_reviews=critic_reviews) + guidelines
            final_messages = [
                {"role": "system", "content": final_prompt},
                {"role": "user", "content": "Please refine the draft into the final response."}
            ]

            # Stream final Judge output, normalizing IDs and model name
            try:
                # Upstream stream read timeout (prevents stalling indefinitely on stalled streams)
                final_stream = await make_api_call(judge_model, final_messages, stream=True, **kwargs)
                async for chunk in final_stream:
                    if isinstance(chunk, bytes):
                        line = chunk.decode("utf-8")
                    else:
                        line = chunk
                    
                    if line.startswith("data: "):
                        line_content = line[6:].strip()
                        if line_content == "[DONE]":
                            yield "data: [DONE]\n\n"
                            continue
                        try:
                            chunk_data = json.loads(line_content)
                            # Normalize chunk ID and model to match the fusion metadata
                            chunk_data["id"] = fusion_id
                            chunk_data["model"] = "model-fusion"
                            yield f"data: {json.dumps(chunk_data)}\n\n"
                        except Exception:
                            # Forward as is if parsing fails
                            yield line
                    else:
                        yield line
            except Exception as e:
                logger.warning(f"Final synthesis streaming failed on {judge_model}: {str(e)}. Falling back to deepseek-v4-pro...")
                try:
                    final_stream = await make_api_call("deepseek-v4-pro", final_messages, stream=True, **kwargs)
                    async for chunk in final_stream:
                        if isinstance(chunk, bytes):
                            line = chunk.decode("utf-8")
                        else:
                            line = chunk
                        
                        if line.startswith("data: "):
                            line_content = line[6:].strip()
                            if line_content == "[DONE]":
                                yield "data: [DONE]\n\n"
                                continue
                            try:
                                chunk_data = json.loads(line_content)
                                chunk_data["id"] = fusion_id
                                chunk_data["model"] = "model-fusion"
                                yield f"data: {json.dumps(chunk_data)}\n\n"
                            except Exception:
                                yield line
                        else:
                            yield line
                except Exception as ex2:
                    logger.error(f"Fallback final synthesis streaming also failed: {str(ex2)}")
                    yield make_chunk("\n\n[Fusion Error] Final synthesis failed. Please try again.", "stop")
                    yield "data: [DONE]\n\n"

        return fusion_stream_generator()

    else:
        # Non-streaming Loop
        logger.info("Executing Non-Streaming Model Fusion (Claude Fable 5 Loop)")
        
        # Phase 1: Panel Drafting
        # Each query_panel_model() is individually capped at 60s via
        # asyncio.wait_for(), so the gather() below returns in ≤60s even for
        # the slowest panel.  The 70s outer timeout is defense-in-depth:
        # if a task escapes the inner timeout (highly unlikely but possible
        # with non-cancellable operations), we bail and proceed to Phase 2
        # with whatever partial results we already collected from completed
        # tasks — the fallback prompt text handles the all-empty case.
        tasks = [query_panel_model(model, messages) for model in panel_models]
        try:
            panel_results = await asyncio.wait_for(asyncio.gather(*tasks), timeout=70)
        except asyncio.TimeoutError:
            logger.warning("Non-streaming Phase 1 gather() timed out (70s). Proceeding with partial results.")
            # gather() cancellation may have lost partial results, but
            # query_panel_model never raises, so we can just re-collect
            # synchronously (all tasks are already done or cancelled).
            panel_results = []
            for i, t in enumerate(tasks):
                if t.done() and not t.cancelled():
                    try:
                        panel_results.append(t.result())
                    except Exception:
                        panel_results.append((panel_models[i], ""))
                else:
                    panel_results.append((panel_models[i], ""))
        panel_responses = ""
        for model_name, content in panel_results:
            if content:
                panel_responses += f"\n--- MODEL: {model_name} ---\n{content}\n"

        if not panel_responses:
            panel_responses = "Panel drafting failed."

        # Phase 2: Draft Synthesis
        draft_messages = [
            {"role": "system", "content": JUDGE_DRAFT_SYSTEM_PROMPT.format(user_request=user_request, panel_responses=panel_responses)},
            {"role": "user", "content": "Please synthesize the drafts."}
        ]
        _, draft_solution = await query_panel_model(judge_model, draft_messages)
        if not draft_solution:
            logger.warning(f"Primary judge {judge_model} failed. Falling back to deepseek-v4-pro for draft synthesis...")
            _, draft_solution = await query_panel_model("deepseek-v4-pro", draft_messages)

        # Phase 3: Critic Review
        critic_prompt = CRITIC_SYSTEM_PROMPT.format(user_request=user_request, draft_solution=draft_solution)
        critic_messages = [
            {"role": "system", "content": critic_prompt},
            {"role": "user", "content": "Please review the draft."}
        ]
        critic_tasks = [query_panel_model(critic, critic_messages) for critic in critic_models]
        critic_results = await asyncio.gather(*critic_tasks)
        critic_reviews = ""
        for model_name, content in critic_results:
            if content:
                critic_reviews += f"\n--- CRITIC: {model_name} ---\n{content}\n"

        # Run local AST compilation audit
        ast_errors = validate_python_code_blocks(draft_solution)
        if ast_errors:
            logger.warning(f"AST Validator found {len(ast_errors)} syntax errors in draft.")
            critic_reviews += "\n--- CRITIC: LOCAL_PYTHON_AST_VALIDATOR ---\n"
            critic_reviews += "The following Python syntax errors were detected during compilation check. Please fix them:\n"
            critic_reviews += "\n".join(ast_errors) + "\n"

        if not critic_reviews:
            critic_reviews = "No critiques generated."

        # Phase 4: Final Refinement
        final_prompt = JUDGE_FINAL_SYSTEM_PROMPT.format(user_request=user_request, draft_solution=draft_solution, critic_reviews=critic_reviews) + guidelines
        final_messages = [
            {"role": "system", "content": final_prompt},
            {"role": "user", "content": "Please refine the draft into the final response."}
        ]
        
        try:
            final_response = await make_api_call(judge_model, final_messages, stream=False, **kwargs)
        except Exception as e:
            logger.warning(f"Final synthesis failed on judge {judge_model}: {str(e)}. Falling back to deepseek-v4-pro...")
            final_response = await make_api_call("deepseek-v4-pro", final_messages, stream=False, **kwargs)
            
        # Normalize response model metadata
        if "model" in final_response:
            final_response["model"] = "model-fusion"
        if "id" in final_response:
            final_response["id"] = fusion_id
        return final_response
